name: Heroku deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Send LINE Notify
    - name: Send "Deployment started"
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: |
          Deployment started
          Repository - ${{ github.repository }}
          Commit - ${{ github.event.head_commit.message }}
          By ${{ github.event.head_commit.author.name }}, ${{ github.event.head_commit.timestamp }}
        
    # Deploying to Heroku
    - name:  Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: suthinan-terminal
        heroku_email: potaezquatro@gmail.com

    # Send LINE Notify
    - name: Send "Deployment failed"
      if: ${{ failure() }}
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: |
          Deployment failed
          Repository - ${{ github.repository }}
          Commit - ${{ github.event.head_commit.message }}
          By ${{ github.event.head_commit.author.name }}, ${{ github.event.head_commit.timestamp }}
    - name: Send "Deployment finished"
      if: ${{ success() }}
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: |
          Deployment finished
          Repository - ${{ github.repository }}
          Commit - ${{ github.event.head_commit.message }}
          By ${{ github.event.head_commit.author.name }}, ${{ github.event.head_commit.timestamp }}